# Generated by Django 5.0.14 on 2025-08-31 03:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SaidaInsumo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantidade', models.PositiveIntegerField()),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('colaborador_entregando', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregas', to='core.colaborador')),
                ('colaborador_retira', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retiradas', to='core.colaborador')),
                ('insumo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.insumo')),
            ],
        ),
    ]
