# Generated by Django 5.0.14 on 2025-09-18 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_remove_colaborador_endereco_colaborador_bairro_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='colaborador',
            name='celular',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='colaborador',
            name='email',
            field=models.EmailField(blank=True, max_length=100, null=True),
        ),
    ]
