# Generated by Django 5.0.14 on 2025-09-18 17:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_colaborador_celular_colaborador_email'),
    ]

    operations = [
        migrations.AddField(
            model_name='saidainsumo',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilo(s)'), ('g', 'Grama(s)'), ('l', 'Litro(s)'), ('un', 'Unidade(s)')], default='un', max_length=5),
        ),
    ]
