# Generated by Django 5.0.14 on 2025-09-18 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_saidainsumo_unidade'),
    ]

    operations = [
        migrations.AlterField(
            model_name='insumo',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilo(s)'), ('g', 'Grama(s)'), ('l', 'Litro(s)'), ('un', 'Unidade(s)')], default='un', max_length=5),
        ),
    ]
