# Generated by Django 5.0.14 on 2025-09-18 23:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_alter_insumo_unidade'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='insumo',
            name='unidade',
        ),
        migrations.AddField(
            model_name='insumo',
            name='unidade_base',
            field=models.CharField(choices=[('g', 'Gramas'), ('ml', 'Mililitros'), ('un', 'Unidade')], default=1, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='insumo',
            name='quantidade',
            field=models.FloatField(help_text='Armazenado em unidade base (g/ml/un)'),
        ),
    ]
