# Generated by Django 5.0.14 on 2025-09-19 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_remove_insumo_unidade_insumo_unidade_base_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='produtopronto',
            name='data_fabricacao',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='produtopronto',
            name='data_validade',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='produtopronto',
            name='preco',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True),
        ),
        migrations.AlterField(
            model_name='saidainsumo',
            name='quantidade',
            field=models.FloatField(),
        ),
        migrations.AlterField(
            model_name='saidainsumo',
            name='unidade',
            field=models.CharField(choices=[('kg', 'Quilo(s)'), ('g', 'Grama(s)'), ('l', 'Litro(s)'), ('ml', 'Mililitro(s)'), ('un', 'Unidade(s)')], default='un', max_length=5),
        ),
    ]
